# Generated by Django 4.1.5 on 2023-01-27 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('asset', models.CharField(choices=[('Phone', 'Phones'), ('Tablet', 'Tablets'), ('Laptop', 'Laptops')], max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='JsonModel',
        ),
    ]
