# Generated by Django 4.1.5 on 2023-01-27 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assetsmodel_delete_customer_delete_jsonmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetsmodel',
            old_name='email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='assetsmodel',
            old_name='name',
            new_name='employee_phone',
        ),
        migrations.RemoveField(
            model_name='assetsmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='assetsmodel',
            name='company_name',
            field=models.CharField(default=datetime.datetime(2023, 1, 27, 13, 13, 55, 970928, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetsmodel',
            name='employee_email',
            field=models.EmailField(default=datetime.datetime(2023, 1, 27, 13, 14, 11, 466173, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetsmodel',
            name='employee_name',
            field=models.CharField(default=datetime.datetime(2023, 1, 27, 13, 14, 20, 162259, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
