# Generated by Django 4.1.5 on 2023-01-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_email_assetsmodel_company_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetsmodel',
            old_name='company_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='assetsmodel',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='assetsmodel',
            old_name='employee_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='assetsmodel',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='assetsmodel',
            name='employee_name',
        ),
    ]
