# Generated by Django 4.1.5 on 2023-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_company_email_assetsmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('asset', models.CharField(choices=[('Phone', 'Phones'), ('Tablet', 'Tablets'), ('Laptop', 'Laptops')], max_length=10)),
                ('checkin_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('asset', models.CharField(choices=[('Phone', 'Phones'), ('Tablet', 'Tablets'), ('Laptop', 'Laptops')], max_length=10)),
                ('checkout_date', models.DateTimeField()),
            ],
        ),
    ]
